# 路径配置
paths:
  output_tmp_dir: "tmp/ocr_results"
  # video_base_dir: "D:\\Videos"
  video_base_dir: "D:\\Downloads\\scrcpy-win64-v2.3.1\\scrcpy-win64-v2.3.1"


# ROI (感兴趣区域) 预设配置
roi_presets:
    "预设: 录屏结果": "X=597, Y=750, W=85, H=45"
    "预设: 直播画面": "X=820, Y=900, W=97, H=46"
    "自定义手动输入": "X=, Y=, W=, H="

ocr_engine:
    det_model_name: 'naive_det'
    rec_model_name: 'en_PP-OCRv4'
    cand_alphabet: '0123456789.'
    font_path: null